// <auto-generated />
namespace Apollo.EF6GettingStarted.Module3.Intro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class indexadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(indexadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201807242125030_indexadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
