// <auto-generated />
using System;
using Apollo.EFCore.Shared.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Apollo.EFCore.Shared.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    partial class RestaurantContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Apollo.EFCore.Shared.Models.Budget", b =>
                {
                    b.Property<int>("BudgetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BudgetType");

                    b.HasKey("BudgetId");

                    b.ToTable("Budget");
                });

            modelBuilder.Entity("Apollo.EFCore.Shared.Models.Cuisine", b =>
                {
                    b.Property<int>("CuisineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CuisineName");

                    b.HasKey("CuisineId");

                    b.ToTable("Cuisines");
                });

            modelBuilder.Entity("Apollo.EFCore.Shared.Models.HeadChef", b =>
                {
                    b.Property<int>("HeadChefId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HeadChefName");

                    b.Property<int>("RestaurantId");

                    b.HasKey("HeadChefId");

                    b.HasIndex("RestaurantId")
                        .IsUnique();

                    b.ToTable("HeadChefs");
                });

            modelBuilder.Entity("Apollo.EFCore.Shared.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HeadChefId");

                    b.Property<int?>("RestaurantBudgetBudgetId");

                    b.Property<string>("RestaurantLocation")
                        .IsRequired();

                    b.Property<string>("RestaurantName")
                        .IsRequired();

                    b.Property<decimal>("RestaurantRating");

                    b.HasKey("RestaurantId");

                    b.HasIndex("HeadChefId")
                        .IsUnique();

                    b.HasIndex("RestaurantBudgetBudgetId");

                    b.ToTable("Restaurants");
                });

            modelBuilder.Entity("Apollo.EFCore.Shared.Models.RestaurantCuisine", b =>
                {
                    b.Property<int>("RestaurantId");

                    b.Property<int>("CuisineId");

                    b.HasKey("RestaurantId", "CuisineId");

                    b.HasIndex("CuisineId");

                    b.ToTable("RestaurantCuisine");
                });

            modelBuilder.Entity("Apollo.EFCore.Shared.Models.HeadChef", b =>
                {
                    b.HasOne("Apollo.EFCore.Shared.Models.Restaurant", "Restaurant")
                        .WithOne("HeadChef")
                        .HasForeignKey("Apollo.EFCore.Shared.Models.HeadChef", "RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Apollo.EFCore.Shared.Models.Restaurant", b =>
                {
                    b.HasOne("Apollo.EFCore.Shared.Models.Budget", "RestaurantBudget")
                        .WithMany()
                        .HasForeignKey("RestaurantBudgetBudgetId");
                });

            modelBuilder.Entity("Apollo.EFCore.Shared.Models.RestaurantCuisine", b =>
                {
                    b.HasOne("Apollo.EFCore.Shared.Models.Cuisine", "Cuisine")
                        .WithMany()
                        .HasForeignKey("CuisineId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Apollo.EFCore.Shared.Models.Restaurant", "Restaurant")
                        .WithMany("RestaurantCuisines")
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
