// <auto-generated />
using System;
using Apollo.ASPNetCore.Module6.RestaurantReviews.EFModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Apollo.ASPNetCore.Module6.RestaurantReviews.Migrations
{
    [DbContext(typeof(RestaurantContext))]
    [Migration("20180823183425_m2m")]
    partial class m2m
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Apollo.ASPNetCore.Module6.RestaurantReviews.Models.Cuisine", b =>
                {
                    b.Property<int>("CuisineId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CuisineName");

                    b.Property<int?>("RestaurantId");

                    b.HasKey("CuisineId");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Cuisine");
                });

            modelBuilder.Entity("Apollo.ASPNetCore.Module6.RestaurantReviews.Models.Greeting", b =>
                {
                    b.Property<int>("GreetingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message");

                    b.HasKey("GreetingId");

                    b.ToTable("Greeting");
                });

            modelBuilder.Entity("Apollo.ASPNetCore.Module6.RestaurantReviews.Models.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RestaurantBudget");

                    b.Property<string>("RestaurantLocation")
                        .IsRequired();

                    b.Property<string>("RestaurantName")
                        .IsRequired();

                    b.Property<decimal>("RestaurantRating");

                    b.HasKey("RestaurantId");

                    b.ToTable("Restaurant");
                });

            modelBuilder.Entity("Apollo.ASPNetCore.Module6.RestaurantReviews.Models.Cuisine", b =>
                {
                    b.HasOne("Apollo.ASPNetCore.Module6.RestaurantReviews.Models.Restaurant")
                        .WithMany("Cuisines")
                        .HasForeignKey("RestaurantId");
                });
#pragma warning restore 612, 618
        }
    }
}
