//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apollo.CSInterfaces.Module3.ServiceRepository.CS.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPeopleService")]
    public interface IPeopleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/GetPeople", ReplyAction="http://tempuri.org/IPeopleService/GetPeopleResponse")]
        Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person[] GetPeople();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/GetPeople", ReplyAction="http://tempuri.org/IPeopleService/GetPeopleResponse")]
        System.Threading.Tasks.Task<Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person[]> GetPeopleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/GetPerson", ReplyAction="http://tempuri.org/IPeopleService/GetPersonResponse")]
        Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person GetPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/GetPerson", ReplyAction="http://tempuri.org/IPeopleService/GetPersonResponse")]
        System.Threading.Tasks.Task<Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person> GetPersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/AddPerson", ReplyAction="http://tempuri.org/IPeopleService/AddPersonResponse")]
        void AddPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/AddPerson", ReplyAction="http://tempuri.org/IPeopleService/AddPersonResponse")]
        System.Threading.Tasks.Task AddPersonAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/UpdatePerson", ReplyAction="http://tempuri.org/IPeopleService/UpdatePersonResponse")]
        void UpdatePerson(string lastName, Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person updatedPerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/UpdatePerson", ReplyAction="http://tempuri.org/IPeopleService/UpdatePersonResponse")]
        System.Threading.Tasks.Task UpdatePersonAsync(string lastName, Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person updatedPerson);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/DeletePerson", ReplyAction="http://tempuri.org/IPeopleService/DeletePersonResponse")]
        void DeletePerson(string lastName, string firstName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/DeletePerson", ReplyAction="http://tempuri.org/IPeopleService/DeletePersonResponse")]
        System.Threading.Tasks.Task DeletePersonAsync(string lastName, string firstName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPeopleServiceChannel : Apollo.CSInterfaces.Module3.ServiceRepository.CS.ServiceReference1.IPeopleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeopleServiceClient : System.ServiceModel.ClientBase<Apollo.CSInterfaces.Module3.ServiceRepository.CS.ServiceReference1.IPeopleService>, Apollo.CSInterfaces.Module3.ServiceRepository.CS.ServiceReference1.IPeopleService {
        
        public PeopleServiceClient() {
        }
        
        public PeopleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeopleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person[] GetPeople() {
            return base.Channel.GetPeople();
        }
        
        public System.Threading.Tasks.Task<Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person[]> GetPeopleAsync() {
            return base.Channel.GetPeopleAsync();
        }
        
        public Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person GetPerson() {
            return base.Channel.GetPerson();
        }
        
        public System.Threading.Tasks.Task<Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person> GetPersonAsync() {
            return base.Channel.GetPersonAsync();
        }
        
        public void AddPerson() {
            base.Channel.AddPerson();
        }
        
        public System.Threading.Tasks.Task AddPersonAsync() {
            return base.Channel.AddPersonAsync();
        }
        
        public void UpdatePerson(string lastName, Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person updatedPerson) {
            base.Channel.UpdatePerson(lastName, updatedPerson);
        }
        
        public System.Threading.Tasks.Task UpdatePersonAsync(string lastName, Apollo.CSInterfaces.Module3.Interfaces.CS.Models.Person updatedPerson) {
            return base.Channel.UpdatePersonAsync(lastName, updatedPerson);
        }
        
        public void DeletePerson(string lastName, string firstName) {
            base.Channel.DeletePerson(lastName, firstName);
        }
        
        public System.Threading.Tasks.Task DeletePersonAsync(string lastName, string firstName) {
            return base.Channel.DeletePersonAsync(lastName, firstName);
        }
    }
}
