// <auto-generated />
namespace Apollo.EF6GettingStarted.Module2.Intro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adduniqueindexcolumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduniqueindexcolumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201807242111153_adduniqueindexcolumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
